### PR TITLE
Prevent panics and data corruption

### PR DESCRIPTION
**Pull request by pascaldekloe**

### CODE REVIEW

**Comment by pascaldekloe** [comment]
UDT still panics. Even MarshalTo. We can't have a service go down due to one malformed package.

**Comment by wmnsk** [comment]
Yeah in the current implementation it might cause panic as I haven’t tested enough yet... 
I think adding the test like `TestPartialStructuredParams` for Message and fixing SEGV-ish issues one by one makes it better, and after that I’m wondering to set up fuzzing(manually or as a part of CI) with go-fuzz.
Would you like to continue working on that? Otherwise, I will.

_Just as an excuse, it was originally born as a part of my testing tools that is to craft and send arbitrary(malicious) packets to see how network equipment behave. Now it’s made public and I want to make it robust enough to be used for other purposes, though._

**Comment by pascaldekloe** [comment]
Fuzzing could work indeed. This <github.com/dvyukov/go-fuzz> is a pleasure to work with. SCCP packages are limited to 256 bytes, with most of the significant ones in the first few positions. You cloud just test **all** combinations.

I'm pretty occupied with hobby projects of my own. Just wanted to contribute a little, since you care. 👍

**Comment by wmnsk** [comment]
Yes certainly this legacy protocol can be tested thoroughly👌

Thank you for your great contributions. I’m happy to attract you to such a minor protocol. Hope I can see you in some other projects as a contributor with what I learned from you 😃

**Pull request merged**
